### PR TITLE
Redesign

### LINKED ISSUE #1: number in vote app to big for styling
_From @sokra on February 20, 2017 7:32_

image

_Copied from original issue: webpack/webpack.js.org#918_

### LINKED ISSUE #3: Redesign
Moving this conversation from webpack/webpack.js.org#409...

@pksjce the CTA for vote buttons, especially on mobile, are definitely still an issue. If someone has a good idea to rectify this, I'd be happy to incorporate it into the design.

> Note: At some point I'll likely be migrating these comps to sketch, but if there are any quick fixes I can make them in the current version. I'll push the current updates to the webpack-design repo as well at some point today.

Here are all the comps for reference:

__Logged Out__

image

__Logged in as a Normal User__

image

__Logged in as an Admin__

image

__Admin Settings Menu__

image

__Mobile__

image

### PR DESCRIPTION
**Pull request by skipjack**
This tackles the redesign discussed in #3. It also contains more code formatting, simplification, and various other improvements imho.

Still need to...

- [x] Handle edit/locked/archived options.
- [x] Handle create topic design (will use the editable `<Topic>` for this).
- [x] Replace currency icon (currently placeholder circle) with webpack shape.
- [x] Handle mobile display (might disable admin features on small screen sizes for simplicity).
- [x] Test `npm link`ed development from the main repo.

Resolves #1 
Resolves #3

### CODE REVIEW

**Comment by skipjack** [comment]
Still working on the mobile display but aside from that this is ready for review. To test in the main site:

- `git checkout port-voting-app`
- `git clone https://github.com/webpack-contrib/voting-app.git`
- `npm link ...`

**Comment by skipjack** [comment]
Ok, pushed the styling changes so the page still looks decent on mobile devices. Here's some screenshots for those who don't have time to pull and test:

## Desktop

Here it is on any screen larger than `720px`:




## Mobile

Here it is on any screen under `720px`:

**Comment by TheLarkInn** [comment]
This looks incredible

**Comment by pksjce** [comment]
This looks so good @skipjack !

**Comment by skipjack** [comment]
@TheLarkInn @pksjce thanks for the feedback! Once @sokra has taken a look I'll merge, publish, and finish webpack/webpack.js.org#1717.

**Comment by skipjack** [comment]
FWIW I think we should take a similar approach for the analyze tool (i.e. build in isolation then integrate into the main site). There are some shared color schemes and other things that could be pushed to a shared `webpack.ui` package. In terms of naming these packages I was planning to use a dot to delineate them from the dash convention (`-`) used for loaders, plugins and utils (i.e. `webpack.ui`, `webpack.vote`, `webpack.analyze`).

**Comment by skipjack** [comment]
Ok starting to wrap this up...

- [ ] Finish testing (specifically with live data)
- [ ] Merge this to master
- [ ] Publish it to npm
- [ ] Consume it from webpack.js.org (i.e. finish webpack/webpack.js.org#1717)

Hoping to have this done tonight.

**Comment by TheLarkInn** [comment]
Let me know if there's any way I can assist.

**Comment by skipjack** [comment]
@TheLarkInn will do. How about this, I'll hit the first three items and then get webpack/webpack.js.org#1717 so it's easy to pull and test. Then I'll give it until tomorrow or thursday to do the actual merge so people can test.

**Comment by skipjack** [comment]
Ok those four items are done but I couldn't fully test production logging in and editing because I'm not aware of a way to get the GitHub OAuth working on `localhost`. Everything should work properly but we may want to be double/triple check after the deployment. You can uncomment the `development` prop to test it with the dev api (`api.dev.js`). Note that you may see errors in the console if you login in dev mode and switch back to prod mode without removing the `voteAppToken` from `localStorage`.

Also, what's our standard for releasing? I used `standard-version` but can't push directly to `master`. I'll create and merge another PR to get the release commits in for now but I'm curious about how we typically manage releases.

**Comment by TheLarkInn** [comment]
Hmm let me check with @bebraw and @d3viant0ne. They would know for sure in terms of deploys from webpack-contrib. Overall this all looks incredible.

**Pull request merged**
