### PR TITLE
feat: include vote keys in tab order

### PR DESCRIPTION
**Pull request by anshumanv**
ref - https://github.com/webpack/webpack.js.org/issues/3444

### CODE REVIEW

**Comment by EugeneHlushko** [comment]
Hi @anshumanv does it work well from mobile device? maybe we can also increase hit area of voting arrows while you are at it?

**Comment by anshumanv** [comment]
Sounds fair, on it.

**Comment by anshumanv** [comment]
Thinking of doubling the area, that should make it reasonably big.

**Comment by EugeneHlushko** [comment]
Just make sure it doesnt break layout, otherwise doubling sounds good 👍 
Please screenshot it if possible

**Comment by anshumanv** [comment]
image

Doubled everything, is this alright or we leave the currency icon as is?

**Comment by EugeneHlushko** [comment]
@anshumanv all right, though i meant if you can double the tap area and not the visuals to, e.g. by using paddings around arrows

**Comment by anshumanv** [comment]
Ah okay, if you think about it that way, padding can help, so we persist the original size of the arrows?

**Comment by EugeneHlushko** [comment]
@anshumanv yeah i'd not touch the design unless we are professional UI/UX designers

**Comment by EugeneHlushko** [comment]
@anshumanv i think a more elegant solution would be to move the actual triangle rendering styles to a pseudo element ::after of the figure, that way you can set any padding/width/height on the figure and just align the pseudo as you like

**Comment by anshumanv** [comment]
Seems reasonable enough, will do. 👍

**Comment by anshumanv** [comment]
Lost track of this, just pushed a commit, PTAL @EugeneHlushko

**Comment by anshumanv** [comment]
cc @EugeneHlushko please let me know if there are any other changes needed.

**Review by EugeneHlushko — APPROVED** [review]

**Comment by EugeneHlushko** [comment]
Thanks!

**Pull request merged**
